- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local

  vars:
    controller_hostname: 
    controller_username: 
    controller_password: 

  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  
  pre_tasks:
    - debug:
        var: controller_credential_types

  roles:
    - {role: redhat_cop.controller_configuration.credential_types, when: controller_credential_types is defined}
